name: terraflux-demo
version: 0.1.2
appVersion: 0.1.0
description: Simple web app by golang
home: https://ggwpp.grean
sources:
  - https://github.com/ggwpp/simple-goweb
maintainers:
  - name: Patipat Ponyanan
    email: patipat@omise.co
engine: gotpl
