name: "GithubAction"
on: [push]

jobs:
  hello_world_job:
    runs-on: "ubuntu-latest"
    name: "Building Docker Image"
    steps:
    - name: "Checkout"
      uses: actions/checkout@v1
    - name: "Build Docker Image"
      run: |
        docker build -t temp .
