name: "GithubAction"
on: [push]

jobs:
  hello_world_job:
    runs-on: "ubuntu-latest"
    name: "A job to say hello"
    steps:
    - name: "before"
      run: |
        ls -la
    - name: "Checkout"
      uses: actions/checkout@v1
    - name: "After"
      run: |
        ls -la
    - name: "Build Docker Image"
      run: |
        docker build -t temp .
