name: "GithubAction"
on: 
 push:
 pull_request:
    types: [opened, reopened]

jobs:
  build_and_test:
    runs-on: "ubuntu-latest"
    name: "Building Docker Image"
    steps:
    - name: "Checkout"
      uses: actions/checkout@v1
    - name: "Build Docker Image"
      run: |
        docker build -t temp .
    - name: "Testing"
      run: |
        echo "Testing something. Should test inside docker"
